[package]
name = "rbbtree"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]

[dev-dependencies]
rand = "0.8.5"
libc = "0.2.126"

[build-dependencies]
rustc_version = "0.2"

[features]